// Package esclient executes HTTP requests against an Elasticsearch cluster,
// handling authentication (none, Basic Auth, API Key, mTLS), TLS (custom CA,
// verification can be disabled) and proxies (from the environment or set per
// cluster). See SPEC.md §5.
package esclient

import (
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"
)

const (
	AuthNone   = "none"
	AuthBasic  = "basic"
	AuthAPIKey = "api_key"
	AuthMTLS   = "mtls"
)

// Params gathers everything needed to establish a connection, including
// secrets. A Params value must never be persisted as-is.
type Params struct {
	URL      string
	AuthType string
	Timeout  time.Duration

	// Basic Auth
	Username string
	Password string

	// API Key (Authorization: ApiKey base64(id:secret))
	APIKeyID     string
	APIKeySecret string

	// TLS
	Verify     bool
	CAFile     string
	ClientCert string
	ClientKey  string
	// KeyPassphrase decrypts ClientKey if the private key is encrypted
	// (legacy PEM format, e.g. a key generated by `openssl -des3`).
	KeyPassphrase string

	// Proxy is the cluster's "proxy:" setting in config.yaml: a proxy URL
	// (http:// or socks5://, without credentials), ProxyNone for a direct
	// connection, or empty to follow the environment. See ProxyFor.
	Proxy string
}

// maxResponseBytes bounds how much of a response is read. A result is
// displayed whole — indented, colorized, searchable — which a terminal can't
// usefully do for hundreds of megabytes, and without a bound such a response
// (a full cluster state, a search with no size limit) would exhaust memory
// before the user could tell why. Past the bound the request is reported as
// failed, with what to do about it, rather than shown cut short: half a JSON
// document is worse than none. A variable only so that tests can lower it.
var maxResponseBytes int64 = 64 << 20

// Client executes requests against an already-authenticated Elasticsearch cluster.
type Client struct {
	baseURL string
	params  Params
	proxy   ProxyInfo
	http    *http.Client
}

// Result is the response of an executed request.
type Result struct {
	StatusCode int
	Duration   time.Duration
	Headers    http.Header
	Body       []byte
}

// New builds a Client from Params, including the TLS configuration.
func New(p Params) (*Client, error) {
	if p.URL == "" {
		return nil, errors.New("missing cluster URL")
	}
	if p.Timeout <= 0 {
		p.Timeout = 120 * time.Second
	}

	tlsConfig := &tls.Config{InsecureSkipVerify: !p.Verify}

	if p.CAFile != "" {
		pool, err := loadCAPool(p.CAFile)
		if err != nil {
			return nil, fmt.Errorf("loading CA %s: %w", p.CAFile, err)
		}
		tlsConfig.RootCAs = pool
	}

	if p.AuthType == AuthMTLS {
		cert, err := loadClientCertificate(p.ClientCert, p.ClientKey, p.KeyPassphrase)
		if err != nil {
			return nil, fmt.Errorf("loading client certificate: %w", err)
		}
		tlsConfig.Certificates = []tls.Certificate{cert}
	}

	// A proxy that can't be used — one reached over TLS, a setting holding
	// credentials — is refused here, before anything is sent anywhere.
	chooseProxy, err := proxyFunc(p.Proxy)
	if err != nil {
		return nil, err
	}
	proxy, err := ProxyFor(p.URL, p.Proxy)
	if err != nil {
		return nil, err
	}

	transport := &http.Transport{TLSClientConfig: tlsConfig, Proxy: chooseProxy}

	return &Client{
		baseURL: strings.TrimRight(p.URL, "/"),
		params:  p,
		proxy:   proxy,
		http: &http.Client{
			Transport: transport,
			Timeout:   p.Timeout,
			// A redirection is shown for what it is — its status and its
			// Location header — never followed. Followed, a 301 or 302 turns
			// a POST, PUT or DELETE into a GET of the new address without a
			// word, and a 307 or 308 replays the request, body included, to
			// wherever the answer points: neither is what the user wrote.
			// curl, which F9 gives the equivalent command for, doesn't
			// follow them either.
			CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse },
		},
	}, nil
}

// Proxy tells which proxy this client's requests go through — the zero
// value if none.
func (c *Client) Proxy() ProxyInfo {
	return c.proxy
}

// Execute sends a method/path request (e.g. "GET", "_cat/indices?v") with an
// optional JSON body, and returns the status, duration, and received body.
func (c *Client) Execute(ctx context.Context, method, path string, body []byte) (*Result, error) {
	url := c.baseURL + "/" + strings.TrimLeft(path, "/")

	var reader io.Reader
	if len(body) > 0 {
		reader = bytes.NewReader(body)
	}

	req, err := http.NewRequestWithContext(ctx, strings.ToUpper(method), url, reader)
	if err != nil {
		return nil, fmt.Errorf("building request: %w", err)
	}
	if len(body) > 0 {
		req.Header.Set("Content-Type", "application/json")
	}
	// No Accept forced to application/json: Elasticsearch takes it into
	// account for content negotiation, including on _cat/* which then
	// switches to JSON instead of its default tabular format (SPEC.md §3.3)
	// — the response format must stay each endpoint's own choice.
	c.applyAuth(req)

	start := time.Now()
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("HTTP call: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes+1))
	if err != nil {
		return nil, fmt.Errorf("reading response: %w", err)
	}
	if int64(len(respBody)) > maxResponseBytes {
		return nil, fmt.Errorf("response larger than %d MB, not displayed: narrow the request down (filter_path, size, h=...)", maxResponseBytes>>20)
	}
	// Measured once the whole body is in: the time the user waited, not just
	// the time to the first byte.
	duration := time.Since(start)

	return &Result{StatusCode: resp.StatusCode, Duration: duration, Headers: resp.Header, Body: respBody}, nil
}

func (c *Client) applyAuth(req *http.Request) {
	switch c.params.AuthType {
	case AuthBasic:
		req.SetBasicAuth(c.params.Username, c.params.Password)
	case AuthAPIKey:
		token := base64.StdEncoding.EncodeToString([]byte(c.params.APIKeyID + ":" + c.params.APIKeySecret))
		req.Header.Set("Authorization", "ApiKey "+token)
	case AuthMTLS, AuthNone:
		// Nothing to add: mTLS authentication happens at the TLS level.
	}
}

func loadCAPool(caFile string) (*x509.CertPool, error) {
	data, err := os.ReadFile(caFile)
	if err != nil {
		return nil, err
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(data) {
		return nil, fmt.Errorf("no valid certificate found in %s", caFile)
	}
	return pool, nil
}

func loadClientCertificate(certFile, keyFile, passphrase string) (tls.Certificate, error) {
	certPEM, err := os.ReadFile(certFile)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("reading certificate %s: %w", certFile, err)
	}
	keyPEM, err := os.ReadFile(keyFile)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("reading key %s: %w", keyFile, err)
	}

	// Two formats of encrypted key exist: PKCS#8 ("BEGIN ENCRYPTED PRIVATE
	// KEY"), what OpenSSL has written by default since 1.1.0, and the legacy
	// PEM encryption ("BEGIN RSA PRIVATE KEY" with a DEK-Info header).
	if block, _ := pem.Decode(keyPEM); block != nil && block.Type == "ENCRYPTED PRIVATE KEY" {
		if passphrase == "" {
			return tls.Certificate{}, fmt.Errorf("the private key %s is encrypted: its passphrase is required", keyFile)
		}
		der, err := decryptPKCS8(block.Bytes, passphrase)
		if err != nil {
			return tls.Certificate{}, fmt.Errorf("decrypting private key %s: %w", keyFile, err)
		}
		keyPEM = pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der})
	} else if passphrase != "" {
		keyPEM, err = decryptPEMKey(keyPEM, passphrase)
		if err != nil {
			return tls.Certificate{}, fmt.Errorf("decrypting private key: %w", err)
		}
	}

	return tls.X509KeyPair(certPEM, keyPEM)
}

// decryptPEMKey decrypts a legacy PEM private key (e.g. "-----BEGIN RSA
// PRIVATE KEY-----" encrypted by openssl with DES/AES-CBC and a "DEK-Info"
// header). The encrypted PKCS#8 format is handled by decryptPKCS8.
//
// x509.DecryptPEMBlock is deprecated, but remains the simplest way to
// decrypt this legacy format without an external dependency.
//
//nolint:staticcheck
func decryptPEMKey(keyPEM []byte, passphrase string) ([]byte, error) {
	block, _ := pem.Decode(keyPEM)
	if block == nil {
		return nil, errors.New("invalid PEM private key")
	}
	if !x509.IsEncryptedPEMBlock(block) {
		return keyPEM, nil
	}
	der, err := x509.DecryptPEMBlock(block, []byte(passphrase))
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(&pem.Block{Type: block.Type, Bytes: der}), nil
}
