package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"

	"termdevtools/internal/testclusters"
	"termdevtools/refdata"
)

// observed is what one real cluster reports: its _cat commands ("GET _cat")
// and, for each, its columns ("GET _cat/<command>?help").
type observed struct {
	target  refdata.Target
	columns map[string][]string
}

func generateCatColumns(targetSpec, outPath string) error {
	clusters, err := testclusters.Parse(targetSpec)
	if err != nil {
		return err
	}

	var observations []observed
	for _, cl := range clusters {
		target, err := cl.Target()
		if err != nil {
			return err
		}
		// The intervals are computed from the names: a cluster that isn't
		// what its name says would date every column wrongly.
		root, err := get(cl.URL + "/")
		if err != nil {
			return fmt.Errorf("%s: %w", cl.Name, err)
		}
		if detected := refdata.DetectTarget(root); detected != target {
			return fmt.Errorf("%s: the cluster at %s reports %q", cl.Name, cl.URL, detected.Name())
		}
		o := observed{target: target, columns: make(map[string][]string)}

		listing, err := get(cl.URL + "/_cat")
		if err != nil {
			return fmt.Errorf("%s: %w", cl.Name, err)
		}
		for _, cmd := range refdata.ParseCatListing(listing) {
			help, err := get(cl.URL + "/_cat/" + cmd + "?help")
			if err != nil {
				return fmt.Errorf("%s: _cat/%s: %w", cl.Name, cmd, err)
			}
			columns := refdata.ParseCatHelp(help)
			if len(columns) == 0 {
				return fmt.Errorf("%s: _cat/%s?help lists no column", cl.Name, cmd)
			}
			o.columns[cmd] = columns
		}
		fmt.Printf("%s: %d _cat commands\n", cl.Name, len(o.columns))
		observations = append(observations, o)
	}
	// Intervals are built from one cluster to the next: whatever order
	// -targets gave them in, each distribution's must be in version order.
	sort.SliceStable(observations, func(i, j int) bool {
		a, b := observations[i].target, observations[j].target
		if a.Distribution != b.Distribution {
			return a.Distribution < b.Distribution
		}
		return a.Version.Compare(b.Version) < 0
	})

	if err := os.WriteFile(outPath, []byte(renderCatColumns(observations)), 0o644); err != nil {
		return err
	}
	fmt.Println("wrote", outPath)
	return nil
}

const catColumnsHeader = `# Columns of the _cat commands, for completion of their h= (displayed
# columns) and s= (sort) parameters (SPEC.md §3.2).
#
# This table is only a fallback: the columns actually offered are asked from
# the connected cluster ("GET _cat/<command>?help"), which is exact whatever
# its version. It is what remains when that request fails, and what tells a
# _cat command apart from any other path.
#
# Format: a "# _cat/<command>" line opens a section, followed by one column
# per line. A section or a column may carry tags restricting it to a
# distribution and version interval (@es >=8.19, @opensearch); a column
# without a tag exists wherever its command does. Only full column names are
# listed, not their short aliases.
#
# Version bounds are deliberately conservative: a column that appeared
# between two of the versions queried is dated from the first one where it
# was seen.
#
# Generated by "go run ./tools/genrefdata catcolumns" from real clusters
# (%s) — do not edit by hand.
`

func renderCatColumns(observations []observed) string {
	var names []string
	for _, o := range observations {
		names = append(names, o.target.Name())
	}

	// Every command, and for each its columns, in a stable order: the layout
	// of the most recent cluster first, anything only older ones have after.
	columnOrder := make(map[string][]string)
	seenColumn := make(map[string]map[string]bool)
	for i := len(observations) - 1; i >= 0; i-- {
		for cmd, columns := range observations[i].columns {
			if seenColumn[cmd] == nil {
				seenColumn[cmd] = make(map[string]bool)
			}
			for _, col := range columns {
				if !seenColumn[cmd][col] {
					seenColumn[cmd][col] = true
					columnOrder[cmd] = append(columnOrder[cmd], col)
				}
			}
		}
	}
	var commands []string
	for cmd := range columnOrder {
		commands = append(commands, cmd)
	}
	sort.Strings(commands)

	var b strings.Builder
	fmt.Fprintf(&b, catColumnsHeader, strings.Join(names, ", "))
	for _, cmd := range commands {
		commandPresence := presence(observations, func(o observed) bool { _, ok := o.columns[cmd]; return ok })
		b.WriteString("\n" + strings.TrimSpace("# _cat/"+cmd+" "+constraintFromPresence(observations, commandPresence, nil)) + "\n")
		for _, col := range columnOrder[cmd] {
			columnPresence := presence(observations, func(o observed) bool { return contains(o.columns[cmd], col) })
			b.WriteString(strings.TrimSpace(col+" "+constraintFromPresence(observations, columnPresence, commandPresence)) + "\n")
		}
	}
	return b.String()
}

func presence(observations []observed, has func(observed) bool) []bool {
	p := make([]bool, len(observations))
	for i, o := range observations {
		p[i] = has(o)
	}
	return p
}

// constraintFromPresence turns "seen on these clusters" into constraint
// tags. within, when given, is the presence of the enclosing command: a
// column present wherever its command is needs no tag of its own.
func constraintFromPresence(observations []observed, present, within []bool) string {
	everywhere := true
	for i := range present {
		expected := within == nil || within[i]
		if present[i] != expected {
			everywhere = false
		}
	}
	if everywhere {
		return ""
	}

	var c refdata.Constraint
	c.ES = rangesFor(observations, present, refdata.Elasticsearch)
	c.OS = rangesFor(observations, present, refdata.OpenSearch)
	return c.String()
}

// rangesFor builds the version intervals of one distribution from the
// clusters queried (in ascending version order) — see rangesFromPresence.
func rangesFor(observations []observed, present []bool, distribution refdata.Distribution) []refdata.Range {
	var versions []refdata.Version
	var seen []bool
	for i, o := range observations {
		if o.target.Distribution == distribution {
			versions = append(versions, o.target.Version)
			seen = append(seen, present[i])
		}
	}
	return rangesFromPresence(versions, seen)
}

func contains(list []string, s string) bool {
	for _, item := range list {
		if item == s {
			return true
		}
	}
	return false
}

func get(url string) ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: HTTP %d: %.200s", url, resp.StatusCode, body)
	}
	return body, nil
}
